@url=http://localhost:3000
@user={{url}}/api/users

#===================
#    TEST USERS
#===================

# --- OK ---
GET {{url}}/health 

###
GET {{url}}/api/db

###
# --- OK ---
POST {{user}}
Content-Type: application/json

{
    "name": "jormanuelge",
    "email": "example2@gmail.com",
    "password": "contraseña1234",
    "role": "STUDENT"
}

###
# --- OK ---
GET {{user}}

###
# --- OK ---
GET {{user}}/students

###
# --- OK ---
PUT {{user}}/1
Content-Type: application/json

{
    "name": "Jorge Actualizado"
}

###
# --- OK ---
DELETE {{user}}/2


#==========================
#       TEST MATERIAS
# cualquiera puede acceder
#==========================

@subject={{url}}/api/subjects

### Crear materia
# --- OK ---
POST {{subject}}
Content-Type: application/json

{
    "name": "Matemáticas",
    "email": "ejemplomateriatest@gamil.com",
    "description": "Álgebra y cálculo básico",
    "password": "1234",
    "professor_id": 1
}

### Obtener todas las materias
# --- OK ---
GET {{subject}}

### Actualizar materia
# --- OK ---
PUT {{subject}}/5
Content-Type: application/json

{
    "name": "Matemáticas Avanzadas",
    "description": "Cálculo integral y diferencial"
}

### Eliminar materia
# --- OK ---
DELETE {{subject}}/5


#======================================
#       TEST MATERIAS
# profesor-materia-alumno y relaciones
#======================================

### Obtener materias de un profesor específico
GET {{}}

### Obtener profesores de una materia específica
GET {{}}